server.port: 8080
spring:
  application.name: comment-service
  datasource:
    url: jdbc:h2:file:~/comments-comment-db;CASE_INSENSITIVE_IDENTIFIERS=TRUE;
    driverClassName: org.h2.Driver
    username: sa
    password: 123

  #Permite acesso remoto
  h2:
    console:
      enabled: true
      settings.web-allow-others: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #Alterar para create-drop em caso de mudanca do schema
    hibernate.ddl-auto: update
    show-sql: true